// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CCM_New.Shared
{
    public partial class JgComplainStatus
    {
        public int Id { get; set; }
        public int? IdCoplain { get; set; }
        public int? Status { get; set; }
    }
}
