// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCM_New.Shared
{
    public partial class ReasonCodeExtended
    {
        public int ReasoncodeId { get; set; }
        public string ReasoncodeName { get; set; }
    }
}