// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace CCM_New.Shared
{
    public partial class TblAttachments
    {
        public int UploadId { get; set; }
        public int ComplaintId { get; set; }
        public string Filename { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
    }
}