// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCM_New.Shared
{
    public partial class TblAsnData
    {
        public string Asn { get; set; }
        public string Asnline { get; set; }
        public DateTime? DelivDate { get; set; }
        public DateTime? Grdate { get; set; }
        public string BillOfLading { get; set; }
        public string VendorShipmentNumber { get; set; }
        public string Vendor { get; set; }
        public string VendorName { get; set; }
        public string Plant { get; set; }
        public string Material { get; set; }
        public string Matdesc { get; set; }
        public string Prodhier { get; set; }
        public int ShipQty { get; set; }
        public int RecvdQty { get; set; }
        public decimal? Shippedstockvalue { get; set; }
        public string Currency { get; set; }
        public string AsnType { get; set; }
    }
}