// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCM_New.Shared
{
    public partial class TblCustomers
    {
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerEmail { get; set; }
        public bool CustomerKeyAccount { get; set; }
        public string CustomerSo { get; set; }
    }
}