// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCM_New.Shared
{
    public partial class TblComplaintTypes
    {
        public int ComplaintTypeId { get; set; }
        public string ComplaintTypeName { get; set; }
    }
}