// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CCM_New.Shared
{
    public partial class TblComplaints
    {
        public int ComplaintId { get; set; }
        public string ComplaintIduf { get; set; }
        public string ShippingPoint { get; set; }
        public string SalesOrganization { get; set; }
        public int DeliveryType { get; set; }
        public DateTime? DeliveryDate { get; set; }
        [ForeignKey("Cust")]
        public string ShiptoCustomerNumber { get; set; }
        public string SoldToCustomerNumber { get; set; }
        public string BillOfLading { get; set; }
        public string ExtDelRef { get; set; }
        [ForeignKey("ReasonCd")]
        public int Reasoncode { get; set; }
        public int ComplaintType { get; set; }
        public Guid RegisteredBy { get; set; }
        public bool? CreateCnDn { get; set; }
        public decimal TotalCnDnValue { get; set; }
        public string CnDnCurrency { get; set; }
        public string CustomerComments { get; set; }
        public string CnDnNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public bool? SendToOriginDc { get; set; }
        public DateTime? SendingDateOriginDc { get; set; }
        public string DcComments { get; set; }
        public bool? SendPodRequest { get; set; }
        public DateTime? SendingDatePodRequest { get; set; }
        public bool? CarrierFeedback { get; set; }
        public DateTime? CarrierFeedbackDate { get; set; }
        public bool? RemarksOnPod { get; set; }
        public string PodComments { get; set; }
        public string CarrierFunloc { get; set; }
        public string CarrierName { get; set; }
        public bool BelowThreshold { get; set; }
        public bool? CnCreated { get; set; }
        public DateTime? CnCreatedDate { get; set; }
        public string ClosureRemarks { get; set; }
        public string ResearchRemarks { get; set; }
        public bool? LiabilityNoteSent { get; set; }
        public bool? LiabilityNoteAccept { get; set; }
        public string CustomerFax { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public bool? PoliceReport { get; set; }
        public DateTime? DcfeedbackReceiveDate { get; set; }
        public string RemarksLsprequest { get; set; }
        public int? Rootcause { get; set; }
        public DateTime? ClaimCreatedDate { get; set; }
        public int? ClaimParty { get; set; }
        public string RadarRef { get; set; }
        public decimal? ClaimAmount { get; set; }
        public int? ClaimCurrency { get; set; }
        public string CreateCnRemarks { get; set; }
        public string LiabilityRemarks { get; set; }
        public bool? PrAvailable { get; set; }
        public decimal? AmountReceived { get; set; }
        public decimal? AmountInvoiced { get; set; }
        public int? InvoicedCurrency { get; set; }
        public string RemarksFinance { get; set; }
        public int? Status { get; set; }
        public string CustomerCnnumber { get; set; }
        public decimal? CustomerCnvalue { get; set; }
        public int? CustomerCncurrency { get; set; }
        public string CustomerCnremarks { get; set; }
        public string CarrierClaimRemarks { get; set; }
        public string InsuranceClaimRemarks { get; set; }
        public DateTime? InvoiceCreatedDate { get; set; }
        public decimal? AmountReceivedInvoice { get; set; }
        public int? LiableParty { get; set; }
        public DateTime? CncustCreatedDate { get; set; }
        public int? FinalRootcause { get; set; }
        public bool? CreateCncust { get; set; }
        public string VendorFunloc { get; set; }
        public string VendorName { get; set; }
        public string CarrierPodremarks { get; set; }
        public bool CncustCreated { get; set; }
        public string RemarksPodnotReceived { get; set; }
        public string CreateCncustRemarks { get; set; }
    

        public TblCustomers Cust { get; set; }

        public TblReasoncodes ReasonCd { get; set; }

    }
}