// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CCM_New.Shared
{
    public partial class TblDcUser
    {
        public int Id { get; set; }

        [ForeignKey("DC")]
        public int DcId { get; set; }
      //  public Guid UserId { get; set; }

        public int UserId { get; set; }

        public TblDc DC { get; set; }
    }
}
