// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CCM_New.Shared
{
    public partial class TblDc
    {
        public int DcId { get; set; }
        public string DcName { get; set; }
        public string Dc { get; set; }
        public string Country { get; set; }
        public double Threshold { get; set; }
        public string CountryCode { get; set; }
        public bool? DcActive { get; set; }
    }
}
