// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCM_New.Shared
{
    public partial class TblRootCauses
    {
        public int RootCauseId { get; set; }
        public string RootCauseName { get; set; }
        public int ComplaintType { get; set; }
        public bool? Active { get; set; }
    }
}