// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CCM_New.Shared
{
    public partial class TblSapData
    {
        public string Vbeln { get; set; }
        public double Posnr { get; set; }
        public DateTime? Erdat { get; set; }
        public string Vstel { get; set; }
        public string Vkorg { get; set; }
        public DateTime? Lfdat { get; set; }
        public string Kunnr { get; set; }
        public string Kunag { get; set; }
        public string Bolnr { get; set; }
        public DateTime? WadatIst { get; set; }
        public DateTime? Wadat { get; set; }
        public string Lifex { get; set; }
        public string Matnr { get; set; }
        public string Werks { get; set; }
        public string Prodh { get; set; }
        public double? Lfimg { get; set; }
        public string Vrkme { get; set; }
        public double? Lgmng { get; set; }
        public string Vgbel { get; set; }
        public double? Vgpos { get; set; }
        public decimal? IcValue { get; set; }
        public string Currency { get; set; }
        public string Artkx { get; set; }
    }
}