// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CCM_New.Shared
{
    public partial class TblSoUser
    {
        public int Id { get; set; }
        [ForeignKey("Sorg")]
        public int So { get; set; }
        public int UserId { get; set; }

        public TblSo Sorg { get; set; }
    }
}
