// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CCM_New.Shared
{
    public partial class TblSo
    {
        public int Id { get; set; }
        public string So { get; set; }
        public string Nso { get; set; }
    }
}
