// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CCM_New.Shared
{
    public partial class TblTasks
    {
        public int TaskId { get; set; }
        public string Task { get; set; }
        public int Allocation { get; set; }
    }
}
