// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CCM_New.Shared
{
    public partial class TblTaskUser
    {
        public int Id { get; set; }
        [ForeignKey("Ta")]
        public int TaskId { get; set; }
        [ForeignKey("Ur")]
        public int UserId { get; set; }
        public bool? ViewTask { get; set; }
        public bool? ChangeTask { get; set; }
        public bool? UpdateTask { get; set; }

        public TblTasks Ta { get; set; }
        public TblUsers Ur { get; set; }

    }
}
